import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased scroll-smooth scrollbar-hide overflow-y-auto lg:px-[20%] px-[5%]`}
      >
        <img className="w-[100vw] inset-0 absolute h-[100vh] rounded-xl -z-10" src="./6495906face286999a890d16d9f1d15d.jpg" alt="" />
        <div className="z-10">
          {children}
        </div>
      </body>
    </html>
  );
}
